name: Fetch YouTube screenwork comments cron task
# 為避免重覆執行，影片留言記錄完會在Youtube_data google sheets 上的 Comments_search_state 記錄各作品留言搜尋並記錄的狀態
# 如想重新執行，要調整 Comments_search_state 中對應的資料

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天台灣早上 8 點

jobs:
  check-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Check RUN_YOUTUBE_VIDEOS_COMMENTS_FETCH_CRON_TASK
        run: |
          if [ "${{ vars.RUN_YOUTUBE_VIDEOS_COMMENTS_FETCH_CRON_TASK }}" != "true" ]; then
            echo "❌ Skip: Github Actions variable RUN_YOUTUBE_VIDEOS_COMMENTS_FETCH_CRON_TASK is not set to 'true'."
            exit 1
          fi

  run-script:
    runs-on: ubuntu-latest
    needs: check-condition
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env from GitHub Secrets and Variables
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env
          echo "YOUTUBE_SPREADSHEET_ID=${{ secrets.YOUTUBE_SPREADSHEET_ID }}" >> .env
          echo "GOOGLE_SHEET_JSON_B64=${{ secrets.GOOGLE_SHEET_JSON_B64 }}" >> .env
          echo "YOUTUBE_SEARCH_COMMENTS_VIDEO_IDS_FOR_SCREENWORK_B64=${{ vars.YOUTUBE_SEARCH_COMMENTS_VIDEO_IDS_FOR_SCREENWORK_B64 }}" >> .env

      - name: Run Python script
        run: python -X dev application/fetch_youtube_screenwork_comments.py
