name: Generate youtube trending reports

on:
  workflow_dispatch: # 允許手動觸發
  schedule:
    - cron: '0 0 28 * *' # UTC時間

permissions:
  contents: write

jobs:
  build-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.11

      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      - name: Create .env from GitHub Secrets
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env
          echo "YOUTUBE_SPREADSHEET_ID=${{ secrets.YOUTUBE_SPREADSHEET_ID }}" >> .env
          echo "GOOGLE_SHEET_JSON_B64=${{ secrets.GOOGLE_SHEET_JSON_B64 }}" >> .env

      # - name: Generate Reports
      #   run: |
      #     for i in 1 2 3; do
      #       python -X dev application/youtube_topic_modeling_pipeline.py && break
      #       echo "Retrying in 30 seconds..."
      #       sleep 30
      #     done

      - name: Commit and push to gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gh-pages || git checkout -b gh-pages

          cp -r docs/* .
          git add .
          git commit -m "Update gh-pages [skip ci]" || echo "No changes to commit"

          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          # git push origin gh-pages
