name: Generate youtube trending reports

on:
  workflow_dispatch: # 允許手動觸發
  schedule:
    - cron: '0 0 28 * *' # 是UTC時間

jobs:
  build-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env from GitHub Secrets
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> .env
          echo "YOUTUBE_SPREADSHEET_ID=${{ secrets.YOUTUBE_SPREADSHEET_ID }}" >> .env
          echo "GOOGLE_SHEET_JSON_B64=${{ secrets.GOOGLE_SHEET_JSON_B64 }}" >> .env

      # - name: Generate Reports
      #   run: |
      #     python -X dev application/youtube_topic_modeling_pipeline.py

      - name: Commit and push to gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 切到 gh-pages branch，如果沒有就建立
          git checkout gh-pages || git checkout -b gh-pages

          # 將生成的檔案複製到 branch 根目錄（或指定資料夾）
          cp -r path/to/generated/html/* .

          # 提交變更
          git add .
          git commit -m "Update gh-pages [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
